# Gradle Properties
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Project Details
jvm_version=17

project_group=de.florianreuth
project_name=Classic4J
project_version=2.3.1-SNAPSHOT
project_description=Java implementation of the ClassiCube and BetaCraft protocol

publish_owner_id=florianreuth
publish_owner_name=Florian Reuth
publish_owner_mail=git@florianreuth.de
